# This is a basic workflow that is manually triggered

name: Progression

on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  progress_bar:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Modifiy the specific files using scripts
        run: .github/scripts/generate_progress.sh
        shell: bash

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "peterbonnesoeur"
          git config --global user.email "maxime.bonn@gmail.com"

          git add -A
          git commit -m "Updated the progression of the challenge"
          git push
